// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfYyGgnHPUZNjClSvhwdzI4RjWCBkuW1s',
    appId: '1:652099771687:web:e97f52f05956a281a71d02',
    messagingSenderId: '652099771687',
    projectId: 'efishery-bank-testing',
    authDomain: 'efishery-bank-testing.firebaseapp.com',
    storageBucket: 'efishery-bank-testing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0bIjxJXkV-5Mwgfm8K9nIcqp_G64KuE',
    appId: '1:652099771687:android:e133441f718ca79ea71d02',
    messagingSenderId: '652099771687',
    projectId: 'efishery-bank-testing',
    storageBucket: 'efishery-bank-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0feVtISSF__QJD4ICsZ57QBFSSDUpmrc',
    appId: '1:652099771687:ios:5b03a9c34a6165dda71d02',
    messagingSenderId: '652099771687',
    projectId: 'efishery-bank-testing',
    storageBucket: 'efishery-bank-testing.appspot.com',
    iosClientId: '652099771687-rqsvqrkjidn6i7o0887r8nhbahp88lgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.efisheryBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0feVtISSF__QJD4ICsZ57QBFSSDUpmrc',
    appId: '1:652099771687:ios:5b03a9c34a6165dda71d02',
    messagingSenderId: '652099771687',
    projectId: 'efishery-bank-testing',
    storageBucket: 'efishery-bank-testing.appspot.com',
    iosClientId: '652099771687-rqsvqrkjidn6i7o0887r8nhbahp88lgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.efisheryBank',
  );
}
